Repository iamgoodbytes/dev5-portfolios, pull requests merged in 2022-11, with the labels that each got.

#154 feat: add Lab 5
  Senne-Christiaens
Labels: ready to approve

#162 Update IsmailElGhamri.md
  IsmailElGhamri.md
Labels: ready to approve

#165 feat: add lab1, lab2, lab4 to Sien Van den Bergh
  SienVandenBergh.md
Labels: ready to approve

#167 feat: add lab4
  michielvanagtmaal.md
Labels: commit messages not ok, ready to approve

#168 feat: add lab5 to SienVandenBergh.md
  SienVandenBergh.md
Labels: ready to approve

#170 feat: mark lab - 5 as done
  Arthur_de_Schietere_de_Lophem.md
Labels: needs update, ready to approve

#174 Sixth labo done!
  JurriënRodi.md
Labels: ready to approve

#175 Update aimane_maadal.md
  aimane_maadal.md
Labels: ready to approve

#176 feat: add lab 6
  GrietBeyens.md
Labels: ready to approve

#177 feat: mark lab - 6 as done
  Arthur_de_Schietere_de_Lophem.md
Labels: ready to approve

#178 feat: add Lab 6
  Senne-Christiaens
Labels: ready to approve

#179 docs: add lab 6
  jef-fasseur.md
Labels: ready to approve

#180 feat: Added lab 6
  GilianSterckx.md
Labels: ready to approve

#181 Feat: add links to labo 6
  LukasHaentjens.md
Labels: ready to approve

#183 docs: added lab 6 link to Marie_Serroyen.md
  Marie_Serroyen.md
Labels: ready to approve

#182 feat: add lab6 to readme file
  LaurenVanDerLinden.md
Labels: ready to approve

#184 feat: add lab 6 link to markdown file
  Marianne_Neuts.md
Labels: ready to approve

#185 feat: add link to lab 6
  liena_paeps.md
Labels: ready to approve

#187 Feat: Added LAB6 link
  BoysangurKhadjiev.md
Labels: ready to approve

#188 Update readme with links to lab 6 repo and live preview
  AlejandroDeWolf.md
Labels: ready to approve

#189 feat: added link to lab 6
  liampeeters.md
Labels: ready to approve

#190 docs: updated readme
  IsmailElGhamri.md
Labels: ready to approve

#173 feat: Add lab 6 to NickBevers.md
  NickBevers.md
Labels: ready to approve

#186 Fix: Added Lab6 Github and live Vercel link
  williamhazevoets.md
Labels: needs update, ready to approve

#191 feat add labo 4
  JeffreyTalemans.md
Labels: ready to approve

#192 feat: finished Lab5
  GilianSterckx.md
Labels: ready to approve

#193 feat: add lab 6
  TimVernaeve.md
Labels: ready to approve

#194 Update larissadeborgher.md
  LarissaDeborgher.md
Labels: ready to approve

#195 feat: add lab 6
  FlorianneDenys.md
Labels: ready to approve

#197 feat: add lab6 to readme
  rickyheylen.md
Labels: ready to approve
