Repository iamgoodbytes/dev5-portfolios, pull requests merged in 2022-10, with the labels that each got.

#50 docs: add lab2 portfolio
  aimane_maadal.md
Labels: codesandbox missing

#61 Feat: add second labo
  JurriënRodi.md
Labels: preview missing

#56 feat: add lab2 to readme file
  LaurenVanDerLinden.md
Labels: needs update

#55 feat: add Lab3 to NickBevers.md
  NickBevers.md
Labels: needs update

#53 docs: update readme with link to lab 2
  AlejandroDeWolf.md
Labels: needs update

#80 feat: add lab2
  marthemaere.md
Labels: preview missing

#79 feat: add link to lab 3
  liena_paeps.md
Labels: needs update

#69 feat: add lab 2 to portfolio
  Arthur_de_Schietere_de_Lophem.md
Labels: live preview missing

#73 Docs: Added link to LAB2
  BoysangurKhadjiev.md
Labels: live preview missing

#81 feat: add lab3 to readme file
  LaurenVanDerLinden.md
Labels: needs update

#82 docs: add lab 3
  jef-fasseur.md
Labels: needs update

#89 Update IsmailElGhamri.md
  IsmailElGhamri.md
Labels: ready to approve

#92 Larissa LAB2
  LarissaDeborgher.md
Labels: commit messages not ok, ready to approve

#93 docs: update readme with link to lab 3
  AlejandroDeWolf.md
Labels: ready to approve

#94 docs: update Marie_Serroyen.md with lab 3 link
  Marie_Serroyen.md
Labels: ready to approve

#95 update robinvanoverloop.md
  robinvanoverloop.md
Labels: ready to approve

#97 feat: Add Lab 3
  Senne-Christiaens
Labels: ready to approve

#100 feat: add lab-3 as done
  Arthur_de_Schietere_de_Lophem.md
Labels: help wanted

#90 Feat: add lab2 to readme file
  LukasHaentjens.md
Labels: ready to approve

#101 feat: add lab 3 link to markdown file
  Marianne_Neuts.md
Labels: ready to approve

#85 feat: add link lab 3
  GrietBeyens.md
Labels: ready to approve

#83 feat: add link lab3
  marthemaere.md
Labels: ready to approve

#86 feat: add Lab3 to nielsverdickt.md
  nielsverdickt.md
Labels: ready to approve

#99 fix: updated codepen with the correct link
  NickBevers.md
Labels: ready to approve

#102 Feat: add third labo
  JurriënRodi.md
Labels: help wanted, ready to approve

#103 feat: Added live link for lab3
  GilianSterckx.md
Labels: ready to approve

#104 Update aimane_maadal.md
  aimane_maadal.md
Labels: needs update

#98 Lab 3 - Weatherheroes
  rickyheylen.md
Labels: ready to approve

#107 fix: add vercel link instead of sandbox
  ElienDeGeetere.md
Labels: ready to approve

#108 Update aimane_maadal.md
  aimane_maadal.md
Labels: ready to approve

#109 feat: Add Lab 4
  Senne-Christiaens
Labels: ready to approve

#110 feat: add lab 4 link to markdown file
  Marianne_Neuts.md
Labels: ready to approve

#112 Feat: add fourth labo
  JurriënRodi.md
Labels: ready to approve

#113 Feat: add labo4
  marthemaere.md
Labels: ready to approve

#114 feat: add lab4 to readme file
  LaurenVanDerLinden.md
Labels: ready to approve

#116 docs: add Lab4 to nielsverdickt.md
  nielsverdickt.md
Labels: ready to approve

#117 build: add link to lab2 repository
  jarne_horemans.md
Labels: ready to approve

#118 docs: added lab 4 link to Marie_Serroyen.md
  Marie_Serroyen.md
Labels: ready to approve

#119 feat: add link lab 4 to GrietBeyens.md
  GrietBeyens.md
Labels: ready to approve

#120 feat: added lab 4 to the document
  GilianSterckx.md
Labels: ready to approve

#122 feat: update FlorianneDenys.md
  FlorianneDenys.md
Labels: ready to approve

#123 Update LadisNelissen.md
  LadisNelissen.md
Labels: ready to approve

#125 feat: add lab 3
  TimVernaeve.md
Labels: ready to approve

#126 feat: add lab 4
  FlorianneDenys.md
Labels: ready to approve

#127 feat: add link to lab 4
  liena_paeps.md
Labels: ready to approve

#128 Docs: LAB3 done + added Vercel live link
  BoysangurKhadjiev.md
Labels: ready to approve

#130 docs: add lab 4
  jef-fasseur.md
Labels: ready to approve

#131 feat: add lab 3 links
  ElienDeGeetere.md
Labels: ready to approve

#133 Docs: Update readMe with labo 2
  LukasVanDyck.md
Labels: ready to approve

#137 feat: add lab 4 to chelseavanbreda.md
  ChelseaVanBreda.md
Labels: ready to approve

#111 docs: update readme with lab 4 link
  AlejandroDeWolf.md
Labels: ready to approve

#91 docs: Added lab 2 & lab 3
  JanaClaessens.md
Labels: ready to approve

#115 feat: mark lab - 4 as done
  Arthur_de_Schietere_de_Lophem.md
Labels: ready to approve

#121 Feat: add next labo(s) + move live previews to Vercel
  LukasHaentjens.md
Labels: ready to approve

#124 feat(JeffreyTalemans.md) add link to vercel
  JeffreyTalemans.md
Labels: ready to approve

#135 feat: added lab 4
  liampeeters.md
Labels: help wanted, ready to approve

#138 Docs: LAB5 done
  BoysangurKhadjiev.md
Labels: ready to approve

#139 docs: add lab 5
  jef-fasseur.md
Labels: ready to approve

#140 Update LadisNelissen.md
  LadisNelissen.md
Labels: ready to approve

#142 Lab 4 - Three.js
  rickyheylen.md
Labels: ready to approve

#143 docs: added lab 5 link to Marie_Serroyen.md
  Marie_Serroyen.md
Labels: ready to approve

#146 feat: add lab5 to readme file
  LaurenVanDerLinden.md
Labels: ready to approve

#147 Lab 4
  robinvanoverloop.md
Labels: ready to approve

#148 feat: add lab 3
  ChelseaVanBreda.md
Labels: ready to approve

#149 feat: add lab4
  TimVernaeve.md
Labels: ready to approve

#150 docs: created SiebeBaerts.md file
  SiebeBaerts.md
Labels: ready to approve

#151 feat: add labo 4
  LukasVanDyck.md
Labels: ready to approve

#144 edit: add lab4
  jarne_horemans.md
Labels: live preview missing

#158 fix labo 2 vercel link add link to correct md file
  JeffreyTalemans.md
Labels: ready to approve

#155 feat: add lab 5 link to markdown file
  Marianne_Neuts.md
Labels: ready to approve

#160 Feat: add lab3
  LarissaDeborgher.md
Labels: ready to approve
